name: Deploy to production (manual)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Simulate deployment
        env:
          IMAGE: ghcr.io/${{ github.repository }}:${{ github.ref_name || 'v1.0.0' }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: |
          echo "Déploiement de l'image $IMAGE sur production..."
          # show masked secrets length (to demonstrate usage without printing it)
          echo "APP_SECRET length: ${#APP_SECRET}"
